spring:
  application:
    name: treino
  datasource:
    url: jdbc:h2:mem:user
    username: sa
    password: 1234
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect  
  h2: 
    console: 
      enabled: true